apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-v2
  labels:
    app: canary-app
    version: v1.1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-app
      version: v1.1
  template:
    metadata:
      labels:
        app: canary-app
        version: v1.1
    spec:
      containers:
      - name: nginx
        image: image: <YOUR DOCKERHUB USERNAME>/canary-app:v1.1  # Replace with your actual username
        imagePullPolicy: Always  # Changed to Always to pull from Docker Hub
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: canary-app-v2
spec:
  selector:
    app: canary-app
    version: v1.1
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
